export interface Medicine {
  /** Optional ID (automatically generated by MongoDB) */
  _id?: string;

  /** Name of the medicine */
  name: string;

  /** Quantity currently in stock */
  quantity: number;

  /** Date when the medicine was manufactured */
  manufacturingDate: string | Date;

  /** Date when the medicine will expire */
  expiryDate: string | Date;

  /** Date when the medicine was entered into the system */
  dateOfEntry: string | Date;

  /** Price in Pakistani Rupees (PKR) */
  price: number;
}

/**
 * Data Transfer Object (DTO) for creating a new medicine entry.
 * Used for POST /api/medicines requests.
 */
export type CreateMedicineDTO = Omit<Medicine, "_id">;

/**
 * DTO for updating an existing medicine entry.
 * Used for PUT /api/medicines/:id requests.
 */
export type UpdateMedicineDTO = Partial<CreateMedicineDTO>;

/**
 * API Response type — what the backend returns after fetching medicines.
 * Helpful when sharing type definitions with the frontend for consistency.
 */
export interface MedicineResponse extends Medicine {
  /** ISO string representation of timestamps */
  manufacturingDate: string;
  expiryDate: string;
  dateOfEntry: string;
  /** MongoDB document identifier as string */
  _id: string;
}
